version: "3.8"

services:
  xml-reader_backend:
    build: ../xml-reader
    container_name: xml-reader_backend
    image: xml-reader_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - xml-reader_database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://xml-reader_database:5432/tempDB
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin

  xml-reader_database:
    container_name: xml-reader_database
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tempDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
